# Exceções

Esse repositório surgiu da minha exploração do
[PEP-3134](https://www.python.org/dev/peps/pep-3134/) sobre encadeamento de
exceções.

Em `masking.py` uma exceção é mascarada. Em `chaining.py` a exceção sofre
encadeamento explícito. Veja os códigos para notar as diferenças. Os outputs
estão neles também.
